language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sky90456/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sky90456/docker-react npm run test 